### ISSUE TITLE
Fix: ClassCastException

### ISSUE THREAD

**Issue by afaneca** [afaneca/myfin-android#27]
```
FATAL EXCEPTION: main
Process: com.afaneca.myfin, PID: 12133
 java.lang.ClassCastException
at a6.j.t(Unknown Source:5)
at j2.j.f(Unknown Source:98)
at k5.a.h(Unknown Source:8)
at y5.b0.run(Unknown Source:104)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8176)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Suppressed: y5.z: [d1{Cancelling}@d9e534, Dispatchers.Main.immediate]
```

**Comment by afaneca** [comment]
Add to revert PR #22 for now. Will look further into it in the future and retry to update AGP then.
